### ISSUE TITLE
some issues need your help 

### ISSUE THREAD

**Issue by mygoda** [michaelrice/rainmaker#1]
when i use pyvmomi to  communication with vcenter， and i hold some long-connection do it。but it always cause vcenter memory very high 。check the vcenter log 。we look so many session。but i only use a number of session. is pyvmomi can not release memory well？

**Comment by michaelrice** [comment]
That is for sure an upstream issue with pyVmomi. It could be related to this: https://github.com/vmware/pyvmomi/issues/194 or something else. It will be best to open an issue with pyVmomi.

**Comment by mygoda** [comment]
i think my issue is not say clearly, and i see this [issue](http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2034127) is ths same to me. i am not confirm is pyvmomi cause problem, but i can see shutdown pyvmomi to connect with vcenter , that vcenter memory go down.this problem also let our vcenter restart. so i want you help me.
